version: '3.3'

services:
  postgres:
    image: postgres:16.4 # Using PostgreSQL version 16.4
    container_name: local-central-db-pgsql-container-16.4
    restart: always
    ports:
      - "5432:5432" # Expose port 5432 for external access
    environment:
      POSTGRES_USER: root # Replace with your username
      POSTGRES_PASSWORD: root # Replace with your password
    volumes:
      - ./dbdata:/var/lib/postgresql/data # Persist data between restarts
    networks:
      - local_central_db_network

networks:
  local_central_db_network:
    external: true
