version: '3.3'
services:
  central_db_8.0.30:
    image: mysql:8.0.30
    container_name: local-central-db-container-8.0.30
    environment:
      MYSQL_ROOT_PASSWORD: Ro@t1234
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./my.cnf:/etc/mysql/my.cnf:ro
    ports:
      - 3306:3306
    networks:
      - local_central_db_network
networks:
  local_central_db_network:
    external: true

